Repository newrelic/nri-rabbitmq, pull requests merged in 2019-02, with the labels that each got.

#22 Added license files
  .papers_config.yml
  papers_manifest.yml
Labels: risk:none

#25 Bump protocol version
  CHANGELOG.md
  rabbitmq-definition.yml
  src/rabbitmq.go
Labels: risk:low

#26 Add suffix for selecting yml while packaging
  Makefile-package.mk
Labels: bug

#27 Changed how queue limiting works and takes into account queue filters
  CHANGELOG.md
  src/rabbitmq.go
Labels: risk:low

#29 Fixed vhost/queue parsing bug
  CHANGELOG.md
  src/args/rabbitmq_args.go
  src/rabbitmq.go
Labels: risk:low
